# Generated by Django 2.1.1 on 2018-09-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0004_auto_20180904_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry_1',
            name='Sample_obj1',
        ),
        migrations.RemoveField(
            model_name='entry_2',
            name='Sample_obj2',
        ),
        migrations.DeleteModel(
            name='Entry_1',
        ),
        migrations.DeleteModel(
            name='Entry_2',
        ),
        migrations.DeleteModel(
            name='SampleModel_1',
        ),
        migrations.DeleteModel(
            name='SampleModel_2',
        ),
        migrations.AddField(
            model_name='entry',
            name='sampleObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SampleApp.SampleModel'),
        ),
    ]
